chore: commit changes for changelog
rudderlabs/rudder-typer pull request #68
Opened 2024-09-12 14:23 UTC by akashrpo

# Thank You for Contributing to RudderTyper!

We sincerely appreciate the time and effort you invest in helping to improve RudderTyper. To make the most of your contribution, we kindly ask that you document your Pull Request thoroughly.

Please note that if the information provided is insufficient, or if the Pull Request does not align with our roadmap, we may need to respectfully thank you for your effort and close the issue.

## Description 📝

> commit changes for changelog

## Respect Earns Respect 👏

We ask that you adhere to our [Code of Conduct](CODE_OF_CONDUCT.md). In summary:

- Use welcoming and inclusive language.
- Respect differing viewpoints and experiences.
- Accept constructive criticism gracefully.
- Focus on what is best for the community.
- Show empathy toward other community members.

2024-09-13 04:55 UTC, saikumarrs requested changes

2024-09-18 11:22 UTC, akashrpo commented on .github/workflows/draft-new-release.yml
>            npm version prerelease --no-commit-hooks
It has been updated to npm run release

2024-09-18 11:44 UTC, saikumarrs commented on .github/workflows/draft-new-release.yml
>            npm version prerelease --no-commit-hooks
Yes, but you don't need this statement in the script now.

2024-09-18 11:57 UTC, saikumarrs approved these changes

2024-09-19 12:12 UTC, merged